---
# tasks file for mysql
 - name: install databases
   apt: name={{item}} state=present update_cache=yes
   with_items:
    - python-mysqldb
    - mysql-server

 - name: ensure mysql server  is started
   service: name=mysql state=started

 - name: allow mysql to listen in all
   lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
        line="bind-address={{ansible_eth1.ipv4.address}}"
   notify: restart mysql

 - name: create database {{ db_name }}
   mysql_db: name={{db_name}} state=present


 - name: create  user {{ db_user_name }}
   mysql_user: name={{ db_user_name }} password={{ db_user_pass }} priv={{ db_name }}.*:ALL host='{{db_host}}' state=present
